### PR TITLE
Prohibit non-members from comitting

### PR DESCRIPTION
**Pull request by qwrtln**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
po4a check

**Comment by DarthGandalf** [comment]
po4a commit

**Comment by DarthGandalf** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit

**Comment by DarthGandalf** [comment]
po4a commit

**Comment by DarthGandalf** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit

**Comment by qwrtln** [comment]
po4a commit

**Pull request closed without merging**
